# https://taskfile.dev

version: '3'

vars:
  PACKAGE_NAME: "TodoTxt"
  USER: "$(whoami)"
  SUBLIME_PACKAGES_DIR: "/Users/{{.USER}}/Library/Application Support/Sublime Text/Packages"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  install:
    desc: Install package
    cmds:
      - cp -r "{{.PACKAGE_NAME}}" "{{.SUBLIME_PACKAGES_DIR}}/"

  remove:
    desc: Remove package
    cmds:
      - rm -rf "{{.SUBLIME_PACKAGES_DIR}}/{{.PACKAGE_NAME}}"

  open:
    desc: Open package directory
    cmds:
      - open "{{.SUBLIME_PACKAGES_DIR}}/{{.PACKAGE_NAME}}"
