# https://taskfile.dev

version: '3'

vars:
  PACKAGE_NAME: "TodoTxt"
  USER: "$(whoami)"
  SUBLIME_PACKAGES_DIR: "/Users/{{.USER}}/Library/Application Support/Sublime Text/Packages/"
  PACKAGE_DIR: "{{.SUBLIME_PACKAGES_DIR}}/{{.PACKAGE_NAME}}"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  install:
    desc: Install package
    cmds:
      - cp -r "{{.PACKAGE_NAME}}" "{{.PACKAGE_DIR}}"

  remove:
    desc: Remove package
    cmds:
      - rm -rf "{{.PACKAGE_DIR}}"
