# https://taskfile.dev

version: '3'

vars:
  USER: "$(whoami)"
  SUBLIME_USER_DATA: "/Users/{{.USER}}/Library/Application Support/Sublime Text/Packages/User/"
  SYNTAX_FILE: "TodoTxt.sublime-syntax"
  SETTINGS_FILE: "TodoTxt.sublime-settings"
  AUTOCOMPLETE_FILE: "todotxt_autocomplete.py"
  COMMANDS_FILE: "todotxt_commands.py"
  DUE_DATES_FILE: "todotxt_due_dates.py"
  NOTES_FILE: "todotxt_notes.py"
  SUBLIME_COMMANDS_FILE: "Default.sublime-commands"

tasks:
  default:
    cmds:
      - task --list
    silent: true

  install:
    desc: Install all files
    cmds:
      - cp {{.SYNTAX_FILE}} "{{.SUBLIME_USER_DATA}}/{{.SYNTAX_FILE}}"
      - cp {{.SETTINGS_FILE}} "{{.SUBLIME_USER_DATA}}/{{.SETTINGS_FILE}}"
      - cp {{.AUTOCOMPLETE_FILE}} "{{.SUBLIME_USER_DATA}}/{{.AUTOCOMPLETE_FILE}}"
      - cp {{.COMMANDS_FILE}} "{{.SUBLIME_USER_DATA}}/{{.COMMANDS_FILE}}"
      - cp {{.DUE_DATES_FILE}} "{{.SUBLIME_USER_DATA}}/{{.DUE_DATES_FILE}}"
      - cp {{.NOTES_FILE}} "{{.SUBLIME_USER_DATA}}/{{.NOTES_FILE}}"
      - cp {{.SUBLIME_COMMANDS_FILE}} "{{.SUBLIME_USER_DATA}}/{{.SUBLIME_COMMANDS_FILE}}"

  open:
    desc: Open the Sublime Text user data directory
    cmds:
      - open "{{.SUBLIME_USER_DATA}}"
